version: '3'

services:
###> doctrine/doctrine-bundle ###
  db:
    image: "mariadb:10.3"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: "Europe/Paris"
    ports:
      - "3306:3306"
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

  php:
    build: ./docker/php
    tty: true
    links:
      - db:db
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "80:80"
      - "443:443"

volumes:
  db-data:

